### ISSUE TITLE
Can't create archive

### ISSUE THREAD

**Issue by jihosan** [lduboeuf/utzipper#14]
**Steps to reproduce**
Try to create a new archive, click on the "Home" button and try to import new files or create a new folder.

**Expected behavior**
Files should get imported and/or a new folder should get created.

**Actual behavior**
After clicking on the button to create an archive, the contents of the click package will be shown in the app. As long as the app is in that state, an archive can be created by clicking on the share button.
After clicking on the "Home" button, no file can be imported anymore and new folders cannot be created.

After clicking on "Home", the log will state following:
- currentDir: QUrl("")
- qml: move to:

Additionally in this state, if the current page is closed and removed from the PageStack and then readded by clicking on create archive, the "Home" button won't work anymore, with the following message in the log:

"qrc:/ArchiveWriter.qml:66: Error: Cannot assign [undefined] to QUrl

**Full log**
[https://pastebin.com/mtwxk0KC](https://pastebin.com/mtwxk0KC)

**Comment by lduboeuf** [comment]
Thanks for the report, could you test if it is fine now with 2.6.1 ?

**Comment by jihosan** [comment]
Unfortunately it doesn't. Now the Home button seemingly does nothing at all.

**In the logs I get:**
lastError - no arguments?

[PERFORMANCE]: Last frame took 39 ms to render.

qml: cleanup

mNewArchiveDir QUrl("file:///home/phablet/.local/share/utzip.lduboeuf/newArchive")

tempDir QUrl("file:///run/user/32011/confined/utzip.lduboeuf")

**Comment by lduboeuf** [comment]
humm just as a test, does /home/phablet/.local/share/utzip.lduboeuf/newArchive exist ?

**Comment by jihosan** [comment]
Actually, the parent folder doesn't exist.

**Comment by lduboeuf** [comment]
fixed by c2308cbf5b8f4911ccdc60b004cb1f3f842f34e6
